site_name: ثبت‌احوال (سروش زنده‌دل)
site_description: دفتری برای نوشته‌ها، درددل‌ها و اشعار
site_author: Soroush Zendedel
site_url: https://soroush-zendedel.github.io/sabte-ahval/

theme:
  name: material
  language: fa
  font: false
  direction: rtl
  custom_dir: overrides
  logo: assets/images/logo2.png
  favicon: assets/images/logo2.png
  palette:
    - scheme: default
      primary: custom
      accent: custom

  features:
    - navigation.instant
    - navigation.top
    # - navigation.expand
    - search.suggest
    - search.highlight
    - header.autohide
    - content.code.copy

extra_css:
  - stylesheets/custom.css
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css

extra_javascript:
  - javascripts/custom.js
  
# nav:
#   - صفحه اصلی: index.md

plugins:
  - search
  # - blog:
  #       blog_dir: .
  #       post_dir: posts
  #       post_date_format: full
  - macros:
        module_name: main
  - awesome-pages
  - tags:
      tags_file: tags.md # با این کار می‌توانید بعدا یک صفحه به نام tags.md بسازید تا لیست همه تگ‌ها آنجا جمع شود
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
  
  - git-revision-date-localized:
        enable_creation_date: true
        type: timeago # یا مقدار date برای نمایش تاریخ دقیق

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html

extra:
  generator: false
  meta:
    - name: google-site-verification
      content: <meta name="google-site-verification" content="1zazcy1c77XqQzgQ472O63fbqTXGxB2ZrFkt2kVu-uo" />
  